image: node:14

cache:
  key: '$CI_BUILD_REF_NAME'
  untracked: true
  paths:
    - node_modules/

stages:
  - prepare
  - verify
  - test
  - publish

before_script:
  - VERSION=$([ ! -z $CI_COMMIT_TAG ] && echo ${CI_COMMIT_TAG} || echo ${CI_COMMIT_REF_NAME})
  - echo VERSION=$VERSION

codestyle:
  stage: verify
  script:
    - npm ci
    - npm run lint
    # - npm audit

node:10:
  stage: test
  image: node:10
  only:
    - /^v\d+\.\d+\.\d+(-rc.\d+|)$/
  script:
    - npm i
    - npm run unit
  coverage: /^All files[^|]*\|[^|]*\s+([\d\.]+)/

node:12:
  stage: test
  image: node:12
  only:
    - /^v\d+\.\d+\.\d+(-rc.\d+|)$/
  script:
    - npm i
    - npm run unit
  coverage: /^All files[^|]*\|[^|]*\s+([\d\.]+)/

node:14:
  stage: test
  image: node:14
  script:
    - npm ci
    - npm run unit
  coverage: /^All files[^|]*\|[^|]*\s+([\d\.]+)/

npm:
  stage: publish
  script:
    - VERSION_TAG=$([[ $CI_COMMIT_TAG == *"-rc"* ]] && echo "next" || echo "latest")
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm ci
    - npm run prepare
    - npm publish --tag $VERSION_TAG
  environment:
    name: npm
    url: https://www.npmjs.com/package/${CI_PROJECT_NAME}
  when: manual
  only:
    - /^v\d+\.\d+\.\d+(-rc.\d+|)$/
